[tool.poetry]
name = "posterization"
version = "0.1.0"
description = ""
authors = ["Ted Chao <cchao8@gmu.edu>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.18"
gco-wrapper = "^3.0.3"
pillow = "^7.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
